const volcanoes={
 krakatau:{name:'Gunung Anak Krakatau',map:'Anak Krakatau • Selat Sunda',level:'SIAGA — LEVEL III',desc:'Aktivitas vulkanik meningkat. Masyarakat diminta mengikuti rekomendasi radius aman dari otoritas resmi.',ash:'± 15.000 ft',ashKm:'± 4,6 km di atas permukaan laut',direction:'Barat Daya',wind:'Angin 18–24 km/jam',time:'03:42 WIB',date:'07 September 2026',marker:[386,318],plume:[430,255,-18]},
 merapi:{name:'Gunung Merapi',map:'Merapi • DIY & Jawa Tengah',level:'SIAGA — LEVEL III',desc:'Aktivitas tetap tinggi pada skenario demo. Perhatikan rekomendasi bahaya guguran dan awan panas dari sumber resmi.',ash:'± 12.000 ft',ashKm:'± 3,7 km di atas permukaan laut',direction:'Barat Laut',wind:'Angin 12–18 km/jam',time:'02:18 WIB',date:'07 September 2026',marker:[460,332],plume:[410,250,-32]},
 semeru:{name:'Gunung Semeru',map:'Semeru • Jawa Timur',level:'SIAGA — LEVEL III',desc:'Erupsi dan guguran masih dapat terjadi pada skenario demo. Hindari area yang direkomendasikan otoritas.',ash:'± 18.000 ft',ashKm:'± 5,5 km di atas permukaan laut',direction:'Tenggara',wind:'Angin 20–27 km/jam',time:'01:56 WIB',date:'07 September 2026',marker:[570,340],plume:[545,270,18]},
 lewotobi:{name:'Lewotobi Laki-laki',map:'Lewotobi Laki-laki • Flores Timur',level:'AWAS — LEVEL IV',desc:'Skenario demo tingkat aktivitas sangat tinggi. Informasi keselamatan harus selalu mengikuti radius dan arahan resmi terbaru.',ash:'± 30.000 ft',ashKm:'± 9,1 km di atas permukaan laut',direction:'Barat',wind:'Angin 22–31 km/jam',time:'00:47 WIB',date:'07 September 2026',marker:[620,325],plume:[530,250,-8]}
};
const cities={
 jakarta:{name:'Jakarta',coord:[675,160],distance:145,base:12},bandarlampung:{name:'Bandar Lampung',coord:[255,205],distance:68,base:34},yogyakarta:{name:'Yogyakarta',coord:[600,300],distance:440,base:8},surabaya:{name:'Surabaya',coord:[745,325],distance:760,base:5},labuanbajo:{name:'Labuan Bajo',coord:[780,370],distance:940,base:3}
};
const sel=id=>document.getElementById(id); const vsel=sel('volcanoSelect'), csel=sel('citySelect');
function updateVolcano(){const v=volcanoes[vsel.value];sel('volcanoTitle').textContent=v.name;sel('levelText').textContent=v.level;sel('statusDesc').textContent=v.desc;sel('ashHeight').textContent=v.ash;sel('ashKm').textContent=v.ashKm;sel('direction').textContent=v.direction;sel('wind').textContent=v.wind;sel('eventTime').textContent=v.time;sel('eventDate').textContent=v.date;sel('mapTitle').textContent=v.map;sel('volcanoMarker').setAttribute('transform',`translate(${v.marker[0]},${v.marker[1]})`);updateTimeline(0);updateImpact()}
function riskFor(score){if(score>=60)return['Risiko tinggi','high'];if(score>=28)return['Perlu pantau','medium'];return['Risiko rendah','low']}
function impactScore(){const c=cities[csel.value];const mods={krakatau:1,merapi:.72,semeru:.6,lewotobi:.46};return Math.min(100,Math.round(c.base*mods[vsel.value]+(csel.value==='bandarlampung'&&vsel.value==='krakatau'?22:0)+(csel.value==='yogyakarta'&&vsel.value==='merapi'?34:0)+(csel.value==='surabaya'&&vsel.value==='semeru'?27:0)+(csel.value==='labuanbajo'&&vsel.value==='lewotobi'?48:0)))}
function updateImpact(){const c=cities[csel.value],score=impactScore(),risk=riskFor(score);sel('impactCity').textContent=c.name;sel('impactDistance').textContent=`± ${c.distance} km dari area simulasi sebaran`;sel('impactScore').textContent=score;sel('riskPill').textContent=risk[0];sel('riskPill').className=`risk-pill ${risk[1]}`;sel('cityMapLabel').textContent=c.name;sel('cityMarker').setAttribute('transform',`translate(${c.coord[0]},${c.coord[1]})`);if(score>=60){sel('impactMessage').textContent='Pada skenario simulasi, wilayah ini berada dekat atau searah dengan proyeksi plume. Pengguna harus segera diarahkan ke rekomendasi resmi terbaru.';sel('adviceList').innerHTML='<div>! Cek rekomendasi otoritas secara berkala</div><div>! Kurangi paparan luar ruang bila ada advisori</div><div>! Siapkan masker dan rencana perjalanan alternatif</div>'}else if(score>=28){sel('impactMessage').textContent='Wilayah ini perlu dipantau karena perubahan arah angin dapat mengubah tingkat paparan dalam beberapa jam.';sel('adviceList').innerHTML='<div>✓ Pantau arah angin dan advisori terbaru</div><div>✓ Cek kualitas udara sebelum aktivitas luar ruang</div><div>✓ Aktifkan notifikasi perubahan kondisi</div>'}else{sel('impactMessage').textContent='Saat ini wilayah yang dipilih berada di luar arah utama sebaran simulasi. Tetap pantau informasi resmi bila kondisi berubah.';sel('adviceList').innerHTML='<div>✓ Tidak ada tindakan khusus pada skenario ini</div><div>✓ Pantau kanal resmi PVMBG/BMKG</div><div>✓ Cek ulang bila arah angin berubah</div>'}}
function updateTimeline(hour){document.querySelectorAll('.timeline-tabs button').forEach(b=>b.classList.toggle('active',Number(b.dataset.hour)===hour));const v=volcanoes[vsel.value],base=v.plume;const shifts={0:[0,0,1],6:[42,-10,1.08],12:[80,-20,1.16],18:[115,-28,1.24]};const s=shifts[hour];const plume=sel('ashPlume');plume.setAttribute('cx',base[0]+s[0]);plume.setAttribute('cy',base[1]+s[1]);plume.setAttribute('rx',215*s[2]);plume.setAttribute('ry',80*s[2]);plume.setAttribute('transform',`rotate(${base[2]} ${base[0]+s[0]} ${base[1]+s[1]})`);sel('ashCore').style.transform=`translate(${s[0]*.55}px,${s[1]*.55}px)`}
document.querySelectorAll('.timeline-tabs button').forEach(b=>b.addEventListener('click',()=>updateTimeline(Number(b.dataset.hour))));vsel.addEventListener('change',updateVolcano);csel.addEventListener('change',updateImpact);sel('checkBtn').addEventListener('click',()=>{updateImpact();sel('impactCard').animate([{transform:'translateY(5px)',opacity:.75},{transform:'translateY(0)',opacity:1}],{duration:260})});
const modal=sel('modal');function openModal(title,text){sel('modalTitle').textContent=title;sel('modalText').textContent=text;modal.classList.add('open');modal.setAttribute('aria-hidden','false')}function closeModal(){modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}
sel('locationBtn').addEventListener('click',()=>openModal('Cek wilayah saya','Pada versi produksi, lokasi dapat dideteksi dengan izin pengguna atau dipilih manual untuk menghitung kedekatan terhadap area sebaran.'));sel('notifyBtn').addEventListener('click',()=>openModal('Notifikasi wilayah','Konsep MVP: pengguna dapat mengikuti satu atau beberapa wilayah dan hanya menerima alert ketika status atau proyeksi dampak berubah secara signifikan.'));sel('modalClose').addEventListener('click',closeModal);sel('modalOk').addEventListener('click',closeModal);modal.addEventListener('click',e=>{if(e.target===modal)closeModal()});
updateVolcano();